"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ScreenProvider } from "@/contexts/screenProvider";
import { ThemeProvider } from "@/contexts/themeProvider";
import { LanguageProvider } from "@/contexts/languageContext";
import RegisterSection from "@/componnent/main/register/register";
import { RegisterSectionProvider } from "@/contexts/registerSec";
import LayoutContent from "./LayoutContent";
import { StatusBannerProvider } from "@/contexts/StatusBanner";
import { LoadingScreenProvider } from "@/contexts/loadingScreen";
import { ClientProvider } from "@/contexts/client";
// import { SocketProvider } from "@/contexts/soket";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { registerSectionExist, setRegisterSectionExist } = useRegisterSection();

  return (
    <html lang="en">

      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>

      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScreenProvider>
            <LanguageProvider>
              <ThemeProvider>
                <RegisterSectionProvider>
                  <StatusBannerProvider>
                    <LoadingScreenProvider>
                      <ClientProvider>
                        {/* <SocketProvider> */}
                          <LayoutContent>{children}</LayoutContent>
                        {/* </SocketProvider> */}
                      </ClientProvider>
                    </LoadingScreenProvider>
                  </StatusBannerProvider>
                </RegisterSectionProvider>
              </ThemeProvider>
            </LanguageProvider>
        </ScreenProvider>
      </body>
      
    </html>
  );
}
