import { LanguageStracture } from "@/types";


export const english = {
    label: "english",
    language: "en",
    nav: {
        home: "Home",
        collection: "Collection",
        collections: "Collections",
        contact: "Contact Us",
        askAi: "AskAi",
        favorite: "Favorite",
        order: "Orders"
    },
    sideMatter: {
        search: "Search",
        theme: {
            system: "System",
            dark: "Dark",
            light: "Light"
        },
        more: "get more",
        allCollections: "All of collections",
        noRes: "No result!",
        loading: "loading",
        aiMode: "ai mode",
        colors: "Colors",
        sizes: "Sizes",
        types: "Types",
        fillOutTheForm: "Fill out this form",
        fullName: "Full Name",
        address: "City ​​and address",
        phone: "Phone Number",
        email: "Email",
        password: "Password",
        rePassword: "Retype Password",
        note: "Note",
        resultsFound: "Results found",
        color: "Color",
        size: "Size",
        type: "Type",
        price: "price",
        name: "name",
        date: "date",
        Oldest: "Oldest",
        newest: "newest",
        cheapest: "cheapest",
        mostExpensive: "most expensive",
        max: "Max",
        min: "Min",
        priceZone: "Price zone",
        all: "all",
        filter: "filter",
        SortBy: "Sort by",
        confirm: "confirm",
    },
    register: "Register",
    signIn: "sign In",
    signUp: "sign Up",
    inputYourName: "inter your first and last name",
    inputYourPhone: "inter your phone",
    inputYourEmail: "inter your email",
    inputYourPassword: "inter your Password",
    inputYourPasswordAgain: "input your password again",
    AlreadyHaveAnAccount: "Already have an account ",
    DontHaveAnAccount: "Dont have an account",
    connection: "connection",
    welcomeMr: "Welcome, Mr.",
    welcomeBackMr: "Welcome back, Mr.",
    thanksForJoining: "Thank you for joining SilverWay! 😊",
    thanksForComingBack: "Thank you for coming back to SilverWay! 😊",
    somethingWentWrongWhileSignUp: "Something went wrong during sign-up!",
    AccountWithTheseNameAndPasswordNotFound: "No account found with this name and password.",
    wrongPassword: "Your password is wrong !",
    allFildAreRequired: "All the field are required !",
    inCart: "In cart",
    addToCart: "Add to cart",
    askAi: "Ask AI",
    contact: "Contact Us",
    aboutUs: "About Us",
    myCart: "My Cart",
    cancel: "Cancel",
    confirmOrder: "Confirm Order",
    totalPrice: "Total price",
    shippingCoast: "Shipping coast",
    totalAmmount: "Total Ammount",
    emptyCart: "your cart is empty",
    filYourCart: "go fil it from",
    here: "here",
    recommended: "Recommended",
    forgotPassword: "Forgot Password!",
    confirmedOrder: "Order has been confirmed successfully!",
    invalidVerificationToken: "invalid Verification Token",
    invalidVerificationTokenParagraph: "The verification link is invalid or has expired. \nPlease request a new link to verify your account.",
    accounntVerified: "Account Verified Successfully",
    accounntVerifiedParagraph: "Your email has been verified and your account is now active. \nYou can now start using all the features.",
    FailedToSendEmail: "Failed To Send Email",
    FailedToSendEmailParagraph: "We encountered an error while attempting to send the email. \nPlease check your email or connection and try again later.",
    GetBackMyAccount: "Get back my account",
    GetBackMyAccountParagraph: "send a verification code to the email you used to create your account.",
    sendingEmailParagraph: "we have send you a verification code to this email",
    resend: "Send again",
    myFavorites: "My Favorites",
    myOrders: "My Orders",
    pending: "pending",
    delivered: "delivered",
    failed: "failed",
    pendingOrders: "Pending Orders",
    failedgOrders: "FailedgOrders",
    deliveredOrders: "DeliveredOrders",
    noOrders: "there is no orders !",
    orderNum: "Order Num",
    purchasesDetails: "Purchases Details",
    product: "Product",
    specification: "Specification",
    quantity: "Quantity",
    price: "Price",
    moreDetails: "More details",
    receiver: "Receiver",
    deliveryPhone: "Delivery phone",
    orderedAt: "Ordered at",
    viewMyOrder: "View My Orders",
    yourInfomations: "Your infomations",
    dateOfBirth: "Date od birth",
    inputYourDateOfBirth: 'enter your date of birth...',
    logOut: "Log Out",
    submit: "Submit",
    searchByAi: "Search by AI",
    orderSummary: "Order Summary",
    orderNow: "Order Now",
    addEvaluation: "Add Opinion",
    evaluations: "Opinions",
    reviewsForProduct: "Reviews for this product",
    noEvaluationsYet: "No opinions yet. Be the first!",
    verifiedPurchasesOnly: "Verified Purchases Only",
    rateThisProduct: "Rate this product",
    writeNotes: "Write your notes...",
    editEvaluation: "Edit Opinion",
    artificialIntelligence: "Artificial Intelligence",
    loading: "Loading",
    noResults: "No results found",
    support: "Customer Support",
    social_directory: "Digital Presence",
    reviews: "reviews",
    opinion: "opinion",
    socialMedia: "Social Media",
    collections: "Collections",
    close: "Close",
    haveGoodShop: "have a good shop with SilverWayShop 💫"


} as LanguageStracture;

export const frensh = {
    label: "français",
    language: "fr",
    nav: {
        home: "Accueil",
        collections: "Collections",
        collection: "Collection",
        contact: "Contactez Nous",
        askAi: "Demande IA",
        favorite: "Favorit",
        order: "commandes"
    },
    sideMatter: {
        search: "Recherche",
        theme: {
            system: "Système",
            dark: "Sombre",
            light: "Clair"
        },
        more: "charger plus",
        allCollections: "Toutes les collections",
        noRes: "Aucun résultat!",
        loading: "chargement",
        aiMode: "mode IA",
        colors: "Couleurs",
        sizes: "Tailles",
        types: "Types",
        fillOutTheForm: "Remplissez ce formulaire",
        fullName: "Nom & Prénom",
        address: "ville & addresse",
        phone: "Numéro de Téléphone",
        email: "Email",
        password: "Mot de passe",
        rePassword: "Retaper le mot de passe",
        note: "Note",
        resultsFound: "Résultats trouvés",
        color: "Couleur",
        size: "Taille",
        type: "Type",
        price: "prix",
        name: "nom",
        date: "date",
        Oldest: "plus ancien",
        newest: "Plus récent",
        cheapest: "moins cher",
        mostExpensive: "plus cher",
        max: "Max",
        min: "Min",
        priceZone: "Zone de prix",
        all: "tout les",
        filter: "filter",
        SortBy: "Trier par",
        confirm: "confirmer",
    },
    register: "Registre",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    inputYourName: "Entrez votre nom",
    inputYourPhone: "Entrez votre telephone",
    inputYourEmail: "Entrez votre email",
    inputYourPassword: "Entrez votre mot de passe",
    inputYourPasswordAgain: "Etrez à nouveau votre mot de passe",
    AlreadyHaveAnAccount: "Vous avez déjà un compte",
    DontHaveAnAccount: "Vous n'avez pas de compte",
    connection: "connection",
    welcomeMr: "Bienvenue, Monsieur.",
    welcomeBackMr: "Bon retour, Monsieur ",
    thanksForJoining: "Merci d’avoir rejoint SilverWay ! 😊",
    thanksForComingBack: "Merci de revenir sur SilverWay ! 😊",
    somethingWentWrongWhileSignUp: "Une erreur s’est produite lors de l’inscription !",
    AccountWithTheseNameAndPasswordNotFound: "Aucun compte trouvé avec ce nom et ce mot de passe.",
    wrongPassword: "votre mot de passe est incorrect",
    allFildAreRequired: "Tous les champs sont requis !",
    inCart: "Dans le panier",
    addToCart: "Ajouter au panier",
    askAi: "Demander à l'IA",
    contact: "Contactez-nous",
    aboutUs: "À propos de nous",
    myCart: "Mon Panier",
    cancel: "Annuler",
    confirmOrder: "Confirmer la commande",
    totalPrice: "Prix total",
    shippingCoast: "Frais de livraison",
    totalAmmount: "Montant total",
    emptyCart: "votre panier est vide",
    filYourCart: "allez le remplir depuis",
    here: "ici",
    recommended: "Recommandé",
    forgotPassword: "Mot de passe oublier!",
    confirmedOrder: "La commande a été confirmée avec succès !",
    invalidVerificationToken: "Jeton de vérification invalide",
    invalidVerificationTokenParagraph: "Le lien de vérification est invalide ou a expiré.\nVeuillez demander un nouveau lien pour vérifier votre compte.",
    accounntVerified: "Compte vérifié avec succès",
    accounntVerifiedParagraph: "Votre e-mail a été vérifié et votre compte est maintenant actif.\nVous pouvez maintenant commencer à utiliser toutes les fonctionnalités.",
    FailedToSendEmail: "Échec de l’envoi de l’e-mail",
    FailedToSendEmailParagraph: "Une erreur s’est produite lors de la tentative d’envoi de l’e-mail.\nVeuillez vérifier votre addresse e-mail ou votre connexion, puis réessayer plus tard.",
    GetBackMyAccount: "Récupérer mon compte",
    GetBackMyAccountParagraph: "Envoyez un code de vérification à l’e-mail que vous avez utilisé pour créer votre compte.",
    sendingEmailParagraph: "Nous vous avons envoyé un code de vérification à cet e-mail.",
    resend: "Envoyer à nouveau",
    myFavorites: "Mes Favoris",
    myOrders: "Mes Commandes",
    pending: "En attente",
    delivered: "Livré",
    failed: "Échoué",
    pendingOrders: "Commandes en attente",
    failedgOrders: "Commandes échouées",
    deliveredOrders: "Commandes livrées",
    noOrders: "Il n'y a pas de commandes !",
    orderNum: "Numéro de commande",
    purchasesDetails: "Détails des achats",
    product: "Produit",
    specification: "Spécification",
    quantity: "Quantité",
    price: "Prix",
    moreDetails: "Plus de détails",
    receiver: "Destinataire",
    deliveryPhone: "Téléphone de livreur",
    orderedAt: "Commandé le",
    viewMyOrder: "Voir mes commandes",
    yourInfomations: "Vos informations",
    dateOfBirth: "Date de naissance",
    inputYourDateOfBirth: "Entrez votre date de naissance...",
    logOut: "Se déconnecter",
    submit: "Envoyer",
    searchByAi: "Recherche par IA",
    orderSummary: "Résumé de la commande",
    orderNow: "Acheter",
    addEvaluation: "Ajouter un avis",
    evaluations: "Avis",
    reviewsForProduct: "Avis pour ce produit",
    noEvaluationsYet: "Pas encore d'avis. Soyez le premier !",
    verifiedPurchasesOnly: "Achats vérifiés uniquement",
    rateThisProduct: "Évaluer ce produit",
    writeNotes: "Écrivez vos notes...",
    editEvaluation: "Modifier l'avis",
    artificialIntelligence: "Intelligence Artificielle",
    loading: "Chargement",
    noResults: "Aucun résultat trouvé",
    support: "Service Client",
    social_directory: "Répertoire Numérique",
    reviews: "révision",
    opinion: "opinion",
    socialMedia: "Réseaux sociaux",
    collections: "Collections",
    close: "fermer",
    haveGoodShop: "Bon shopping avec SilverWayShop 💫"


} as LanguageStracture;

















export const languagesDispo = [frensh, english]

export const activeLanguage = frensh;