import { LanguageStracture } from "@/types";

export const english = {
    label: "english",
    language: "en",
    nav: {
        home: "Home",
        collection: "Collection",
        collections: "Collections",
        contact: "Contact Us",
        askAi: "AskAi",
        favorite: "Favorite",
        order: "Orders"
    },
    sideMatter: {
        search: "Search",
        theme: {
            system: "System",
            dark: "Dark",
            light: "Light"
        },
        more: "get more",
        allCollections: "All of collections",
        noRes: "No result!",
        loading: "loading",
        aiMode: "ai mode",
        colors: "Colors",
        sizes: "Sizes",
        types: "Types",
        fillOutTheForm: "Fill out this form",
        fullName: "Full Name",
        adress: "City ​​and address",
        phone: "Phone Number",
        password: "Password",
        rePassword: "Retype Password",
        note: "Note",
        resultsFound: "Results found",
        color: "Color",
        size: "Size",
        type: "Type",
        price: "price",
        name: "name",
        date: "date",
        Oldest: "Oldest",
        newest: "newest",
        cheapest: "cheapest",
        mostExpensive: "most expensive",
        max: "Max",
        min: "Min",
        priceZone: "Price zone",
        all: "all",
        filter: "filter",
        SortBy: "Sort by",
        confirm: "confirm",
    },
    register: "Register",
    signIn: "sign In",
    signUp: "sign Up",
    inputYourName: "inter your first and last name",
    inputYourPhone: "inter your phone",
    inputYourPassword: "inter your Password",
    inputYourPasswordAgain: "input your password again",
    AlreadyHaveAnAccount: "Already have an account ",
    DontHaveAnAccount: "Dont have an account",
    connection: "connection",
    welcomeMr: "Welcome, Mr.",
    welcomeBackMr: "Welcome back, Mr.",
    thanksForJoining: "Thank you for joining SilverWay! 😊",
    thanksForComingBack: "Thank you for coming back to SilverWay! 😊",
    somethingWentWrongWhileSignUp: "Something went wrong during sign-up!",
    AccountWithTheseNameAndPasswordNotFound: "No account found with this name and password.",
    allFildAreRequired: "All the field are required !",
    inCart: "In cart",
    addToCart: "Add to cart",
    askAi: "Ask AI",
    contact: "Contact Us",
    aboutUs: "About Us",
    myCart: "My Cart",
    cancel: "Cancel",
    confirmOrder: "Confirm Order",
    totalPrice: "Total price",
    shippingCoast: "Shipping coast",
    totalAmmount: "Total Ammount",
    emptyCart: "your cart is empty",
    filYourCart: "go fil it from",
    here: "here",
    recommended: "Recommended",
    forgotPassword: "Forgot Password!"

} as LanguageStracture;

export const frensh = {
    label: "français",
    language: "fr",
    nav: {
        home: "Accueil",
        collections: "Collections",
        collection: "Collection",
        contact: "Contactez Nous",
        askAi: "Demande IA",
        favorite: "Favori",
        order: "commandes"
    },
    sideMatter: {
        search: "Recherche",
        theme: {
            system: "Système",
            dark: "Sombre",
            light: "Clair"
        },
        more: "charger plus",
        allCollections: "Toutes les collections",
        noRes: "Aucun résultat!",
        loading: "chargement",
        aiMode: "mode IA",
        colors: "Couleurs",
        sizes: "Tailles",
        types: "Types",
        fillOutTheForm: "Remplissez ce formulaire",
        fullName: "Nom & Prénom",
        adress: "ville & adresse",
        phone: "Numéro de Téléphone",
        password: "Mot de passe",
        rePassword: "Retaper le mot de passe",
        note: "Note",
        resultsFound: "Résultats trouvés",
        color: "Couleur",
        size: "Taille",
        type: "Type",
        price: "prix",
        name: "nom",
        date: "date",
        Oldest: "plus ancien",
        newest: "Plus récent",
        cheapest: "moins cher",
        mostExpensive: "plus cher",
        max: "Max",
        min: "Min",
        priceZone: "Zone de prix",
        all: "tout les",
        filter: "filter",
        SortBy: "Trier par",
        confirm: "confirmer",
    },
    register: "Registre",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    inputYourName: "Entrez votre nom",
    inputYourPhone: "Entrez votre telephone",
    inputYourPassword: "Entrez votre mot de passe",
    inputYourPasswordAgain: "Etrez à nouveau votre mot de passe",
    AlreadyHaveAnAccount: "Vous avez déjà un compte",
    DontHaveAnAccount: "Vous n'avez pas de compte",
    connection: "connection",
    welcomeMr: "Bienvenue, Monsieur.",
    welcomeBackMr: "Bon retour, Monsieur ",
    thanksForJoining: "Merci d’avoir rejoint SilverWay ! 😊",
    thanksForComingBack: "Merci de revenir sur SilverWay ! 😊",
    somethingWentWrongWhileSignUp: "Une erreur s’est produite lors de l’inscription !",
    AccountWithTheseNameAndPasswordNotFound: "Aucun compte trouvé avec ce nom et ce mot de passe.",
    allFildAreRequired: "Tous les champs sont requis !",
    inCart: "Dans le panier",
    addToCart: "Ajouter au panier",
    askAi: "Demander à l'IA",
    contact: "Contactez-nous",
    aboutUs: "À propos de nous",
    myCart: "Mon Panier",
    cancel: "Annuler",
    confirmOrder: "Confirmer la commande",
    totalPrice: "Prix total",
    shippingCoast: "Frais de livraison",
    totalAmmount: "Montant total",
    emptyCart: "votre panier est vide",
    filYourCart: "allez le remplir depuis",
    here: "ici",
    recommended: "Recommandé",
    forgotPassword: "Mot de passe oublier!"



} as LanguageStracture;

export const languagesDispo = [frensh, english]

export const activeLanguage = frensh;